In [ ]:
import polars as pl
import polars.selectors as cs
from polars import DataFrame
from sklearn.datasets import fetch_covtype

from polars_ml import Pipeline
from polars_ml.model_selection import KFold
from polars_ml.model_selection.metrics import evaluate_classification_metrics

bunch = fetch_covtype(as_frame=True)
df: DataFrame = pl.from_pandas(bunch.data).with_columns(pl.from_pandas(bunch.target))  # type: ignore
df

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

shape: (581_012, 55)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Soil_Type_ ┆ Soil_Type_ ┆ Soil_Type_ ┆ Cover_Type │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ 37         ┆ 38         ┆ 39         ┆ ---        │
│ f64       ┆ f64    ┆ f64   ┆ _Hydrolo…   ┆   ┆ ---        ┆ ---        ┆ ---        ┆ i32        │
│           ┆        ┆       ┆ ---         ┆   ┆ f64        ┆ f64        ┆ f64        ┆            │
│           ┆        ┆       ┆ f64         ┆   ┆            ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2596.0    ┆ 51.0   ┆ 3.0   ┆ 258.0       ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 5          │
│ 2590.0    ┆ 56.0   ┆ 2.0   ┆ 212.0       ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 5          │
│ 2804.0    ┆ 139.0  ┆ 9.0   ┆ 268.0       ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 2          │
│ 2785.0    ┆ 155.0  ┆ 18.0  ┆ 242.0       ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 2          │
│ 2595.0    ┆ 45.0   ┆ 2.0   ┆ 153.0       ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 5          │
│ …         ┆ …      ┆ …     ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2396.0    ┆ 153.0  ┆ 20.0  ┆ 85.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 3          │
│ 2391.0    ┆ 152.0  ┆ 19.0  ┆ 67.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 3          │
│ 2386.0    ┆ 159.0  ┆ 17.0  ┆ 60.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 3          │
│ 2384.0    ┆ 170.0  ┆ 15.0  ┆ 60.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 3          │
│ 2383.0    ┆ 165.0  ┆ 13.0  ┆ 60.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 3          │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [2]:
df = df.with_columns(
    pl.concat_str(cs.starts_with("Soil_Type_").cast(pl.UInt8).cast(pl.String)).alias(
        "Soil_Type"
    ),
    pl.concat_str(
        cs.starts_with("Wilderness_Area_").cast(pl.UInt8).cast(pl.String)
    ).alias("Wilderness_Area"),
    pl.col("Cover_Type").cast(pl.String),
).drop(cs.starts_with("Soil_Type_"), cs.starts_with("Wilderness_Area_"))
numerical_columns = [
    "Elevation",
    "Aspect",
    "Slope",
    "Horizontal_Distance_To_Hydrology",
    "Vertical_Distance_To_Hydrology",
    "Horizontal_Distance_To_Roadways",
    "Hillshade_9am",
    "Hillshade_Noon",
    "Hillshade_3pm",
    "Horizontal_Distance_To_Fire_Points",
]
categorical_columns = ["Soil_Type", "Wilderness_Area"]
df

shape: (581_012, 13)
┌───────────┬────────┬───────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ Elevation ┆ Aspect ┆ Slope ┆ Horizontal_ ┆ … ┆ Horizontal ┆ Cover_Type ┆ Soil_Type  ┆ Wilderness │
│ ---       ┆ ---    ┆ ---   ┆ Distance_To ┆   ┆ _Distance_ ┆ ---        ┆ ---        ┆ _Area      │
│ f64       ┆ f64    ┆ f64   ┆ _Hydrolo…   ┆   ┆ To_Fire_Po ┆ str        ┆ str        ┆ ---        │
│           ┆        ┆       ┆ ---         ┆   ┆ …          ┆            ┆            ┆ str        │
│           ┆        ┆       ┆ f64         ┆   ┆ ---        ┆            ┆            ┆            │
│           ┆        ┆       ┆             ┆   ┆ f64        ┆            ┆            ┆            │
╞═══════════╪════════╪═══════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2596.0    ┆ 51.0   ┆ 3.0   ┆ 258.0       ┆ … ┆ 6279.0     ┆ 5          ┆ 0000000000 ┆ 1000       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000010 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2590.0    ┆ 56.0   ┆ 2.0   ┆ 212.0       ┆ … ┆ 6225.0     ┆ 5          ┆ 0000000000 ┆ 1000       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000010 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2804.0    ┆ 139.0  ┆ 9.0   ┆ 268.0       ┆ … ┆ 6121.0     ┆ 2          ┆ 0000000000 ┆ 1000       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0100000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2785.0    ┆ 155.0  ┆ 18.0  ┆ 242.0       ┆ … ┆ 6211.0     ┆ 2          ┆ 0000000000 ┆ 1000       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000001 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2595.0    ┆ 45.0   ┆ 2.0   ┆ 153.0       ┆ … ┆ 6172.0     ┆ 5          ┆ 0000000000 ┆ 1000       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000010 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ …         ┆ …      ┆ …     ┆ …           ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2396.0    ┆ 153.0  ┆ 20.0  ┆ 85.0        ┆ … ┆ 837.0      ┆ 3          ┆ 0100000000 ┆ 0010       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2391.0    ┆ 152.0  ┆ 19.0  ┆ 67.0        ┆ … ┆ 845.0      ┆ 3          ┆ 0100000000 ┆ 0010       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2386.0    ┆ 159.0  ┆ 17.0  ┆ 60.0        ┆ … ┆ 854.0      ┆ 3          ┆ 0100000000 ┆ 0010       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2384.0    ┆ 170.0  ┆ 15.0  ┆ 60.0        ┆ … ┆ 864.0      ┆ 3          ┆ 0100000000 ┆ 0010       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
│ 2383.0    ┆ 165.0  ┆ 13.0  ┆ 60.0        ┆ … ┆ 875.0      ┆ 3          ┆ 0100000000 ┆ 0010       │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ 0000000000 ┆            │
│           ┆        ┆       ┆             ┆   ┆            ┆            ┆ …          ┆            │
└───────────┴────────┴───────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [3]:
if False:
    (
        Pipeline()
        .plot.histogram(numerical_columns, out_dir="hist")
        .plot.histogram(numerical_columns, "Cover_Type", out_dir="hist_by_cover_type")
        .plot.histogram(numerical_columns, "Soil_Type", out_dir="hist_by_soil_type")
        .plot.histogram(
            numerical_columns, "Wilderness_Area", out_dir="hist_by_wilderness_area"
        )
        .plot.scatter(
            numerical_columns, numerical_columns, hue="Cover_Type", out_dir="scatter"
        )
        .transform(df)
    )

In [ ]:
import lightgbm as lgb

metrics = []
for train_idx, valid_idx in KFold(
    n_splits=5, shuffle=True, seed=42, stratify="Cover_Type"
).split(df):
    train_df = df.select(pl.all().gather(train_idx))
    valid_df = df.select(pl.all().gather(valid_idx))

    model = (
        Pipeline()
        .label_encode("Cover_Type", "Soil_Type", "Wilderness_Area", maintain_order=True)
        .gbdt.lightgbm(
            pl.exclude("Cover_Type"),
            "Cover_Type",
            {"objective": "multiclass", "num_class": 8},
            train_kwargs={"callbacks": [lgb.early_stopping(10)]},
        )
        .horizontal.argmax(cs.starts_with("lightgbm_"), value_name="lightgbm")
        .with_columns(
            pl.col("lightgbm")
            .list.first()
            .str.extract(r"lightgbm_(\d+)")
            .cast(pl.UInt8)
        )
    )

    model.fit(train_df, valid_df)
    valid_pred_df = model.transform(valid_df)
    metrics.append(
        evaluate_classification_metrics(
            valid_pred_df,
            "Cover_Type",
            y_pred_class="lightgbm",
            y_pred_proba_prefix="lightgbm_",
            n_classes=8,
        )
    )

pl.concat(metrics)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.006951 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2220
[LightGBM] [Info] Number of data points in the train set: 464807, number of used features: 12
[LightGBM] [Info] Start training from score -4.114264
[LightGBM] [Info] Start training from score -0.718259
[LightGBM] [Info] Start training from score -1.008935
[LightGBM] [Info] Start training from score -3.343853
[LightGBM] [Info] Start training from score -2.788111
[LightGBM] [Info] Start training from score -3.510237
[LightGBM] [Info] Start training from score -5.354529
[LightGBM] [Info] Start training from score -34.538776
Training until validation scores don't improve for 10 rounds
Did not meet early stopping. Best iteration is:
[100]	train's multi_logloss: 0.350211	valid's multi_logloss: 0.38639

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/metrics/_ranking.py:379: UndefinedMetricWarning: Only one class is present in y_true. ROC AUC score is not defined in that case.
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.003969 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2224
[LightGBM] [Info] Number of data points in the train set: 464808, number of used features: 12
[LightGBM] [Info] Start training from score -4.114266
[LightGBM] [Info] Start training from score -0.718257
[LightGBM] [Info] Start training from score -1.008937
[LightGBM] [Info] Start training from score -3.343855
[LightGBM] [Info] Start training from score -2.788113
[LightGBM] [Info] Start training from score -3.510239
[LightGBM] [Info] Start training from score -5.354532
[LightGBM] [Info] Start training from score -34.538776
Training until validation scores don't improve for 10 rounds