In [7]:
import lightgbm as lgb
import polars as pl
import polars.selectors as cs
from polars import DataFrame
from sklearn.datasets import load_digits

from polars_ml import Pipeline
from polars_ml.model_selection import KFold, train_test_split
from polars_ml.model_selection.metrics import evaluate_classification_metrics

bunch = load_digits(as_frame=True)
df: DataFrame = pl.from_pandas(bunch.data).with_columns(pl.from_pandas(bunch.target))  # type: ignore
df

shape: (1_797, 65)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬────────┐
│ pixel_0_0 ┆ pixel_0_1 ┆ pixel_0_2 ┆ pixel_0_3 ┆ … ┆ pixel_7_5 ┆ pixel_7_6 ┆ pixel_7_7 ┆ target │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---    │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ i64    │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪════════╡
│ 0.0       ┆ 0.0       ┆ 5.0       ┆ 13.0      ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0      │
│ 0.0       ┆ 0.0       ┆ 0.0       ┆ 12.0      ┆ … ┆ 10.0      ┆ 0.0       ┆ 0.0       ┆ 1      │
│ 0.0       ┆ 0.0       ┆ 0.0       ┆ 4.0       ┆ … ┆ 16.0      ┆ 9.0       ┆ 0.0       ┆ 2      │
│ 0.0       ┆ 0.0       ┆ 7.0       ┆ 15.0      ┆ … ┆ 9.0       ┆ 0.0       ┆ 0.0       ┆ 3      │
│ 0.0       ┆ 0.0       ┆ 0.0       ┆ 1.0       ┆ … ┆ 4.0       ┆ 0.0       ┆ 0.0       ┆ 4      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …      │
│ 0.0       ┆ 0.0       ┆ 4.0       ┆ 10.0      ┆ … ┆ 9.0       ┆ 0.0       ┆ 0.0       ┆ 9      │
│ 0.0       ┆ 0.0       ┆ 6.0       ┆ 16.0      ┆ … ┆ 6.0       ┆ 0.0       ┆ 0.0       ┆ 0      │
│ 0.0       ┆ 0.0       ┆ 1.0       ┆ 11.0      ┆ … ┆ 6.0       ┆ 0.0       ┆ 0.0       ┆ 8      │
│ 0.0       ┆ 0.0       ┆ 2.0       ┆ 10.0      ┆ … ┆ 12.0      ┆ 0.0       ┆ 0.0       ┆ 9      │
│ 0.0       ┆ 0.0       ┆ 10.0      ┆ 14.0      ┆ … ┆ 12.0      ┆ 1.0       ┆ 0.0       ┆ 8      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴────────┘

In [8]:
train_idx, valid_idx = train_test_split(
    df, 0.2, stratify="target", shuffle=True, seed=42
)

train_df = df.select(pl.all().gather(train_idx))
valid_df = df.select(pl.all().gather(valid_idx))

model = (
    Pipeline()
    .with_columns(cs.starts_with("pixel") / 255)
    .concat(
        Pipeline().reduction.umap(
            pl.exclude("target"),
            include_input=False,
            model_kwargs={"n_components": 2},
        ),
        Pipeline().select("target"),
        how="horizontal",
    )
)
model.fit(train_df, valid_df)
train_pred_df = model.transform(train_df)
valid_pred_df = model.transform(valid_df)

train_plotter = (
    Pipeline()
    .with_columns(pl.col("target").cast(pl.String))
    .plot.scatter("umap_0", "umap_1", "target", out_dir="umap_train")
)
train_plotter.transform(train_pred_df)

valid_plotter = (
    Pipeline()
    .with_columns(pl.col("target").cast(pl.String))
    .plot.scatter("umap_0", "umap_1", "target", out_dir="umap_valid")
)
valid_plotter.transform(valid_pred_df)

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
100%|██████████| 1/1 [00:00<00:00,  4.84it/s]
100%|██████████| 1/1 [00:00<00:00,  4.52it/s]

shape: (355, 3)
┌───────────┬───────────┬────────┐
│ umap_0    ┆ umap_1    ┆ target │
│ ---       ┆ ---       ┆ ---    │
│ f32       ┆ f32       ┆ str    │
╞═══════════╪═══════════╪════════╡
│ -1.086824 ┆ -9.144072 ┆ 0      │
│ 13.046141 ┆ 7.346072  ┆ 1      │
│ 13.849186 ┆ 6.206506  ┆ 2      │
│ 10.152876 ┆ -6.255383 ┆ 3      │
│ -0.781368 ┆ 3.103586  ┆ 4      │
│ …         ┆ …         ┆ …      │
│ 18.141415 ┆ 1.098071  ┆ 7      │
│ 7.982846  ┆ -0.006209 ┆ 5      │
│ 13.277157 ┆ 6.539607  ┆ 8      │
│ -0.244665 ┆ -8.958592 ┆ 0      │
│ 9.504601  ┆ -2.514426 ┆ 9      │
└───────────┴───────────┴────────┘

In [11]:
metrics = []
for train_idx, valid_idx in KFold(
    n_splits=3, shuffle=True, seed=42, stratify="target"
).split(df):
    train_df = df.select(pl.all().gather(train_idx))
    valid_df = df.select(pl.all().gather(valid_idx))

    model = (
        Pipeline()
        .with_columns(cs.starts_with("pixel") / 255)
        .concat(
            Pipeline().reduction.umap(
                pl.exclude("target"),
                include_input=False,
                model_kwargs={"n_components": 2},
            ),
            Pipeline().select("target"),
            how="horizontal",
        )
        .gbdt.lightgbm(
            pl.exclude("target"),
            "target",
            {"objective": "multiclass", "num_class": 10},
            train_kwargs={"callbacks": [lgb.early_stopping(10)]},
        )
        .horizontal.argmax(cs.starts_with("lightgbm_"), value_name="lightgbm")
        .with_columns(
            pl.col("lightgbm")
            .list.first()
            .str.extract(r"lightgbm_(\d+)")
            .cast(pl.UInt8)
        )
    )

    model.fit(train_df, valid_df)
    valid_pred_df = model.transform(valid_df)
    metrics.append(
        evaluate_classification_metrics(
            valid_pred_df,
            "target",
            y_pred_class="lightgbm",
            y_pred_proba_prefix="lightgbm_",
            n_classes=10,
        )
    )

pl.concat(metrics)

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000044 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 1195, number of used features: 2
[LightGBM] [Info] Start training from score -2.315217
[LightGBM] [Info] Start training from score -2.290111
[LightGBM] [Info] Start training from score -2.315217
[LightGBM] [Info] Start training from score -2.281880
[LightGBM] [Info] Start training from score -2.298410
[LightGBM] [Info] Start training from score -2.290111
[LightGBM] [Info] Start training from score -2.298410
[LightGBM] [Info] Start training from score -2.306778
[LightGBM] [Info] Start training from score -2.332311
[LightGBM] [Info] Start training from score -2.298410
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[29]	train's multi_logloss: 0.0182109	valid's multi_logloss: 0.155336

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000044 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 1198, number of used features: 2
[LightGBM] [Info] Start training from score -2.309285
[LightGBM] [Info] Start training from score -2.292618
[LightGBM] [Info] Start training from score -2.317724
[LightGBM] [Info] Start training from score -2.284388
[LightGBM] [Info] Start training from score -2.292618
[LightGBM] [Info] Start training from score -2.292618
[LightGBM] [Info] Start training from score -2.292618
[LightGBM] [Info] Start training from score -2.309285
[LightGBM] [Info] Start training from score -2.334819
[LightGBM] [Info] Start training from score -2.300917
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[26]	train's multi_logloss: 0.0362375	valid's multi_logloss: 0.21145

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000040 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 1201, number of used features: 2
[LightGBM] [Info] Start training from score -2.311786
[LightGBM] [Info] Start training from score -2.286889
[LightGBM] [Info] Start training from score -2.320225
[LightGBM] [Info] Start training from score -2.286889
[LightGBM] [Info] Start training from score -2.295119
[LightGBM] [Info] Start training from score -2.286889
[LightGBM] [Info] Start training from score -2.295119
[LightGBM] [Info] Start training from score -2.303418
[LightGBM] [Info] Start training from score -2.337320
[LightGBM] [Info] Start training from score -2.303418
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[31]	train's multi_logloss: 0.0203859	valid's multi_logloss: 0.0969227

/home/hoge/polars-ml/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:151: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

shape: (3, 13)
┌──────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ accuracy ┆ balanced_a ┆ precision ┆ precision ┆ … ┆ cohen_kap ┆ roc_auc_o ┆ roc_auc_o ┆ log_loss │
│ ---      ┆ ccuracy    ┆ _macro    ┆ _weighted ┆   ┆ pa_score  ┆ vr        ┆ vo        ┆ ---      │
│ f64      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│          ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.9701   ┆ 0.970046   ┆ 0.970974  ┆ 0.971306  ┆ … ┆ 0.966778  ┆ 0.994389  ┆ 0.994398  ┆ 0.155336 │
│ 0.956594 ┆ 0.956288   ┆ 0.957757  ┆ 0.957534  ┆ … ┆ 0.951767  ┆ 0.989554  ┆ 0.989555  ┆ 0.21145  │
│ 0.974832 ┆ 0.97454    ┆ 0.9757    ┆ 0.975619  ┆ … ┆ 0.972034  ┆ 0.998205  ┆ 0.998201  ┆ 0.096923 │
└──────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘