In [7]:
import lightgbm as lgb
import polars as pl
import polars.selectors as cs
from polars import DataFrame
from sklearn.datasets import fetch_20newsgroups

from polars_ml import Pipeline
from polars_ml.model_selection import KFold, train_test_split
from polars_ml.model_selection.metrics import evaluate_classification_metrics

data, target = fetch_20newsgroups(return_X_y=True)
df = DataFrame({"text": data, "target": target})
df

shape: (11_314, 2)
┌─────────────────────────────────┬────────┐
│ text                            ┆ target │
│ ---                             ┆ ---    │
│ str                             ┆ i64    │
╞═════════════════════════════════╪════════╡
│ From: lerxst@wam.umd.edu (wher… ┆ 7      │
│ From: guykuo@carson.u.washingt… ┆ 4      │
│ From: twillis@ec.ecn.purdue.ed… ┆ 4      │
│ From: jgreen@amber (Joe Green)… ┆ 1      │
│ From: jcm@head-cfa.harvard.edu… ┆ 14     │
│ …                               ┆ …      │
│ From: jim.zisfein@factory.com … ┆ 13     │
│ From: ebodin@pearl.tufts.edu    ┆ 4      │
│ S…                              ┆        │
│ From: westes@netcom.com (Will … ┆ 3      │
│ From: steve@hcrlgw (Steven Col… ┆ 1      │
│ From: gunning@cco.caltech.edu … ┆ 8      │
└─────────────────────────────────┴────────┘

In [2]:
with pl.Config(
    set_tbl_rows=20, set_fmt_str_lengths=1000, set_fmt_table_cell_list_len=1000
):
    # n-grams
    display(
        df.lazy()
        .select(pl.col("text").str.split(""))
        .with_row_index("row_index")
        .explode("text")
        .with_columns(pl.cum_count("row_index").over("row_index").alias("index"))
        .rolling("index", period="3i", group_by="row_index", offset="-1i")
        .agg("text")
        .with_columns(pl.col("text").list.join("").alias("text"))
        .group_by("text")
        .len()
        .sort("len", descending=True)
        .collect()
    )

shape: (279_719, 2)
┌──────┬────────┐
│ text ┆ len    │
│ ---  ┆ ---    │
│ str  ┆ u32    │
╞══════╪════════╡
│      ┆ 486643 │
│  th  ┆ 229942 │
│ ---  ┆ 202857 │
│ the  ┆ 185141 │
│ he   ┆ 143481 │
│ ing  ┆ 89084  │
│  to  ┆ 76920  │
│  an  ┆ 75792  │
│ to   ┆ 71198  │
│ and  ┆ 69706  │
│ …    ┆ …      │
│ HJ^  ┆ 1      │
│ ?:!  ┆ 1      │
│ \HE  ┆ 1      │
│ A5+  ┆ 1      │
│ `ow  ┆ 1      │
│ sQu  ┆ 1      │
│ |)>  ┆ 1      │
│ A2Z  ┆ 1      │
│ R4Z  ┆ 1      │
│ ?A#  ┆ 1      │
└──────┴────────┘

In [3]:
with pl.Config(
    set_tbl_rows=20, set_fmt_str_lengths=1000, set_fmt_table_cell_list_len=1000
):
    display(
        df.lazy()
        .select(pl.col("text").str.split(" "))
        .explode("text")
        .group_by("text")
        .len()
        .sort("len", descending=not True)
        .collect()
    )

shape: (427_021, 2)
┌────────────────┬────────┐
│ text           ┆ len    │
│ ---            ┆ ---    │
│ str            ┆ u32    │
╞════════════════╪════════╡
│ $315           ┆ 1      │
│ 	My            ┆        │
│ norris@mit.edu ┆ 1      │
│ Seeking        ┆        │
│ 91109          ┆ 1      │
│                ┆        │
│                ┆        │
│ universal      ┆ 1      │
│ supreme        ┆        │
│ weak.          ┆ 1      │
│ >              ┆        │
│ >But           ┆        │
│ to             ┆ 1      │
│ provide        ┆        │
│                ┆        │
│ prosperity.    ┆ 1      │
│ (pronounce     ┆ 1      │
│ to:            ┆ 1      │
│                ┆        │
│ Michael        ┆        │
│ Nussbaum)      ┆ 1      │
│ Subject:       ┆        │
│ …              ┆ …      │
│ I              ┆ 31184  │
│ that           ┆ 31310  │
│ in             ┆ 34707  │
│ is             ┆ 36661  │
│ and            ┆ 47081  │
│ a              ┆ 52312  │
│ of             ┆ 61504  │
│ to             ┆ 64169  │
│ the            ┆ 115263 │
│                ┆ 660661 │
└────────────────┴────────┘

In [8]:
metrics = []
for train_idx, valid_idx in KFold(
    n_splits=5, shuffle=True, seed=42, stratify="target"
).split(df):
    train_df = df.select(pl.all().gather(train_idx))
    valid_df = df.select(pl.all().gather(valid_idx))

    model = (
        Pipeline()
        .text.tfidf_truncated_svd(
            "text", out_dir="tfidf_truncated_svd", svd_kwargs={"n_components": 100}
        )
        .drop("text")
        .gbdt.lightgbm(
            pl.exclude("target"),
            "target",
            {"objective": "multiclass", "num_class": 20},
            train_kwargs={"callbacks": [lgb.early_stopping(10)]},
        )
        .horizontal.argmax(cs.starts_with("lightgbm_"), value_name="lightgbm")
        .with_columns(
            pl.col("lightgbm")
            .list.first()
            .str.extract(r"lightgbm_(\d+)")
            .cast(pl.UInt8)
        )
    )

    model.fit(train_df, valid_df)
    valid_pred_df = model.transform(valid_df)
    metrics.append(
        evaluate_classification_metrics(
            valid_pred_df,
            "target",
            y_pred_class="lightgbm",
            y_pred_proba_prefix="lightgbm_",
            n_classes=20,
        )
    )

pl.concat(metrics)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002622 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 9045, number of used features: 100
[LightGBM] [Info] Start training from score -3.159325
[LightGBM] [Info] Start training from score -2.963638
[LightGBM] [Info] Start training from score -2.952988
[LightGBM] [Info] Start training from score -2.952988
[LightGBM] [Info] Start training from score -2.974403
[LightGBM] [Info] Start training from score -2.948760
[LightGBM] [Info] Start training from score -2.961499
[LightGBM] [Info] Start training from score -2.946653
[LightGBM] [Info] Start training from score -2.940357
[LightGBM] [Info] Start training from score -2.942451
[LightGBM] [Info] Start training from score -2.936181
[LightGBM] [Info] Start training from score -2.944550
[LightGBM] [Info] Start training from score -2.952988
[LightGBM] [Info] Start training from score -2.946653
[LightGBM] [Info] Start training from score -2.948760
[LightGBM] [Info] Start training from score -2.938267
[LightGBM] [Info] Start training from score -3.032325
[LightGBM] [Info] Start training from score -2.998500
[LightGBM] [Info] Start training from score -3.191074
[LightGBM] [Info] Start training from score -3.402857
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[76]	train's multi_logloss: 0.00291173	valid's multi_logloss: 0.674872
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.008993 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 9048, number of used features: 100
[LightGBM] [Info] Start training from score -3.159656
[LightGBM] [Info] Start training from score -2.963970
[LightGBM] [Info] Start training from score -2.951204
[LightGBM] [Info] Start training from score -2.953320
[LightGBM] [Info] Start training from score -2.974734
[LightGBM] [Info] Start training from score -2.949092
[LightGBM] [Info] Start training from score -2.961831
[LightGBM] [Info] Start training from score -2.946984
[LightGBM] [Info] Start training from score -2.940688
[LightGBM] [Info] Start training from score -2.942783
[LightGBM] [Info] Start training from score -2.936513
[LightGBM] [Info] Start training from score -2.944881
[LightGBM] [Info] Start training from score -2.951204
[LightGBM] [Info] Start training from score -2.946984
[LightGBM] [Info] Start training from score -2.949092
[LightGBM] [Info] Start training from score -2.938598
[LightGBM] [Info] Start training from score -3.030366
[LightGBM] [Info] Start training from score -2.998832
[LightGBM] [Info] Start training from score -3.191405
[LightGBM] [Info] Start training from score -3.403189
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[73]	train's multi_logloss: 0.00344292	valid's multi_logloss: 0.780178
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002054 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 9050, number of used features: 100
[LightGBM] [Info] Start training from score -3.159877
[LightGBM] [Info] Start training from score -2.964191
[LightGBM] [Info] Start training from score -2.951425
[LightGBM] [Info] Start training from score -2.953541
[LightGBM] [Info] Start training from score -2.974955
[LightGBM] [Info] Start training from score -2.949313
[LightGBM] [Info] Start training from score -2.962052
[LightGBM] [Info] Start training from score -2.947205
[LightGBM] [Info] Start training from score -2.940909
[LightGBM] [Info] Start training from score -2.940909
[LightGBM] [Info] Start training from score -2.936734
[LightGBM] [Info] Start training from score -2.945102
[LightGBM] [Info] Start training from score -2.951425
[LightGBM] [Info] Start training from score -2.947205
[LightGBM] [Info] Start training from score -2.949313
[LightGBM] [Info] Start training from score -2.938819
[LightGBM] [Info] Start training from score -3.030587
[LightGBM] [Info] Start training from score -2.999053
[LightGBM] [Info] Start training from score -3.191626
[LightGBM] [Info] Start training from score -3.400093
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[75]	train's multi_logloss: 0.00307613	valid's multi_logloss: 0.734564
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001994 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 9054, number of used features: 100
[LightGBM] [Info] Start training from score -3.160319
[LightGBM] [Info] Start training from score -2.964633
[LightGBM] [Info] Start training from score -2.951867
[LightGBM] [Info] Start training from score -2.953983
[LightGBM] [Info] Start training from score -2.973235
[LightGBM] [Info] Start training from score -2.947647
[LightGBM] [Info] Start training from score -2.962494
[LightGBM] [Info] Start training from score -2.947647
[LightGBM] [Info] Start training from score -2.939261
[LightGBM] [Info] Start training from score -2.941351
[LightGBM] [Info] Start training from score -2.937176
[LightGBM] [Info] Start training from score -2.945544
[LightGBM] [Info] Start training from score -2.951867
[LightGBM] [Info] Start training from score -2.947647
[LightGBM] [Info] Start training from score -2.947647
[LightGBM] [Info] Start training from score -2.939261
[LightGBM] [Info] Start training from score -3.031029
[LightGBM] [Info] Start training from score -2.999495
[LightGBM] [Info] Start training from score -3.192068
[LightGBM] [Info] Start training from score -3.400535
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[70]	train's multi_logloss: 0.00455536	valid's multi_logloss: 0.7837
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001965 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 25500
[LightGBM] [Info] Number of data points in the train set: 9059, number of used features: 100
[LightGBM] [Info] Start training from score -3.160871
[LightGBM] [Info] Start training from score -2.963046
[LightGBM] [Info] Start training from score -2.952419
[LightGBM] [Info] Start training from score -2.954535
[LightGBM] [Info] Start training from score -2.973787
[LightGBM] [Info] Start training from score -2.948199
[LightGBM] [Info] Start training from score -2.963046
[LightGBM] [Info] Start training from score -2.946096
[LightGBM] [Info] Start training from score -2.939813
[LightGBM] [Info] Start training from score -2.941903
[LightGBM] [Info] Start training from score -2.937728
[LightGBM] [Info] Start training from score -2.946096
[LightGBM] [Info] Start training from score -2.952419
[LightGBM] [Info] Start training from score -2.946096
[LightGBM] [Info] Start training from score -2.948199
[LightGBM] [Info] Start training from score -2.937728
[LightGBM] [Info] Start training from score -3.031581
[LightGBM] [Info] Start training from score -2.997832
[LightGBM] [Info] Start training from score -3.192620
[LightGBM] [Info] Start training from score -3.401087
Training until validation scores don't improve for 10 rounds
Early stopping, best iteration is:
[67]	train's multi_logloss: 0.00545389	valid's multi_logloss: 0.759939

shape: (5, 13)
┌──────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ accuracy ┆ balanced_a ┆ precision ┆ precision ┆ … ┆ cohen_kap ┆ roc_auc_o ┆ roc_auc_o ┆ log_loss │
│ ---      ┆ ccuracy    ┆ _macro    ┆ _weighted ┆   ┆ pa_score  ┆ vr        ┆ vo        ┆ ---      │
│ f64      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64      │
│          ┆ f64        ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆          │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.801675 ┆ 0.797298   ┆ 0.805051  ┆ 0.805225  ┆ … ┆ 0.791078  ┆ 0.984423  ┆ 0.984258  ┆ 0.674872 │
│ 0.774051 ┆ 0.768932   ┆ 0.780627  ┆ 0.780766  ┆ … ┆ 0.76197   ┆ 0.979743  ┆ 0.979611  ┆ 0.780178 │
│ 0.791519 ┆ 0.788024   ┆ 0.797092  ┆ 0.796805  ┆ … ┆ 0.780384  ┆ 0.981272  ┆ 0.981136  ┆ 0.734564 │
│ 0.776549 ┆ 0.770384   ┆ 0.78574   ┆ 0.785969  ┆ … ┆ 0.764582  ┆ 0.978876  ┆ 0.978625  ┆ 0.7837   │
│ 0.779157 ┆ 0.772988   ┆ 0.783035  ┆ 0.786777  ┆ … ┆ 0.767374  ┆ 0.980193  ┆ 0.979889  ┆ 0.759939 │
└──────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘